version: '3'

services:

  postgres_dev:                                
    image: postgres:13
    container_name: postgres_dev
    env_file: .env
    restart: always
    environment:                            #config de ambiente
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:                                  #porta de exposição
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}", "-h", "${DB_HOST}"]
      interval: 2s
      timeout: 2s
      retries: 100